apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: solutions/argocd/python-manifests
    repoURL: https://github.com/Nithin47TA/python-helloworld
    targetRevision: HEAD
  syncPolicy: {}